### ISSUE TITLE
error stop_factor_lr

### ISSUE THREAD

**Issue by ghost** [tornadomeet/mxnet-face#1]
Thx your share when I run this model and I found "lr_scheduler       = mx.lr_scheduler.FactorScheduler(step=5*max(int(epoch_size \* 1), 1), factor=0.8, stop_factor_lr=5e-5),"
error"TypeError: **init**() got an unexpected keyword argument 'stop_factor_lr'" what does it mean?
and I use your mxnet version

**Comment by tornadomeet** [comment]
hello,do you rebuild the face mxnet branch and Python interface? stop_factor_lr used when we use factor lr, because factor lr will let lr be smaller and smaller, so stop_factor_lr is the min lr in the whole training.

**Comment by csgcmai** [comment]
I just test last night using the newly build mxnet, i.e., 0.7.0 and found that the stop_factor_lr introduces the error. Maybe I should read the doc for more details.

**Comment by tornadomeet** [comment]
hello @csgcmai , the latest mxnet has support stop_factor_lr, so  do can you post your error here?

**Comment by csgcmai** [comment]
I will run this command later and then post the err msg here. Currently I simply delete that param.
