### ISSUE TITLE
打扰下，运行时出现da symbol = sym.load('%s-symbol.json' % prefix)错误

### ISSUE THREAD

**Issue by dadaxxxx** [tornadomeet/mxnet-face#13]
打扰下，运行时出现如下错误，请问是啥原因造成的啊？

Traceback (most recent call last):
  File "predict.py", line 85, in <module>
    main()
  File "predict.py", line 16, in main
    _, arg_params, aux_params = mx.model.load_checkpoint(args.model_load_prefix, args.model_load_epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 363, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 958, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op Moon of type MoonOutput: [17:07:13] src/operator/operator.cc:19: Cannot find Operator MoonOutput in registry

**Comment by tornadomeet** [comment]
https://github.com/tornadomeet/mxnet-face#before-runing

**Comment by zivCheng** [comment]
i have follow the instructor of before-running. The problem still exist. And i have try to fix this problem, but i found that there is no any MoonOutput type in mxnet. Do you try to create this with your own?

> Z:\sample\mxnet-face\attribute>python ./predict.py --img aaa.jpg
> INFO:root:Namespace(gpus=None, img='aaa.jpg', model_load_epoch=82, model_load_prefix='../model/lightened_moon/lightened_moon_fuse', opencv='../model/opencv/cascade.xml', pad=None, size=128)
> [14:53:20] Z:\Library\mxnet-master\source\dmlc-core\include\dmlc/logging.h:235: [14:53:20] Z:\Library\mxnet-master\source\src\operator\operator.cc:19: Cannot find Operator MoonOutput in registry
> Traceback (most recent call last):
>   File "./predict.py", line 83, in <module>
>     main()
>   File "./predict.py", line 14, in main
>     _, arg_params, aux_params = mx.model.load_checkpoint(args.model_load_prefix, args.model_load_epoch)
>   File "C:\Miniconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\model.py", line 364, in load_checkpoint
>     symbol = sym.load('%s-symbol.json' % prefix)
>   File "C:\Miniconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.py", line 958, in load
>     check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
>   File "C:\Miniconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 77, in check_call
>     raise MXNetError(py_str(_LIB.MXGetLastError()))
> mxnet.base.MXNetError: Failed loading Op Moon of type MoonOutput: [14:53:20] Z:\Library\mxnet-master\source\src\operator\operator.cc:19: Cannot find Operator MoonOutput in registry

**Comment by tornadomeet** [comment]
hello, please read before run carefully. `using my slightly changed mxnet branch face for training.`

**Comment by tornadomeet** [comment]
also when testing, the moon in not in official mxnet, https://github.com/tornadomeet/mxnet/tree/face/src/operator

**Comment by xingdi1990** [comment]
So, should we train the model first and then run the predict.py code?
