### ISSUE TITLE
请教如何修改light-moon？

### ISSUE THREAD

**Issue by charleslipku** [tornadomeet/mxnet-face#14]
你好，请问如果我只想用celebA数据训练cnn来预测40 个face attribute，应该如何修改light-moon模型啊？是不是不需要fuse就ok？还有就是最后同时有40个output，现有的方法是不是通过moon output来实现的啊？

**Comment by tornadomeet** [comment]
the code in attribute is trained only with celeba, you can look at it.

**Comment by charleslipku** [comment]
@tornadomeet Can I use built-in SoftMaxOutput instead of moon output?

**Comment by tornadomeet** [comment]
maybe you can do it, but you should prepare your data more carefully.

**Comment by charleslipku** [comment]
@tornadomeet if I want to use your demo first, do I need to download you mxnet branch to replace my onw?

**Comment by charleslipku** [comment]
I followed your instruction, but I still come to the error: Failed loading Op Moon of type MoonOutput: [01:03:19] src/operator/operator.cc:19: Cannot find Operator MoonOutput in registry

**Comment by tornadomeet** [comment]
are you sure is the face branch?

**Comment by camel007** [comment]
I use 'git clone --brach face --recursive git@github.com:tornadomeet/mxnet.git mxnet4face'
make -j16
cd python 
python setup.py install

but i still got "Failed loading Op Moon of type MoonOutput: [01:03:19] src/operator/operator.cc:19: Cannot find Operator MoonOutput in registry"

@charleslipku 
Did you resolve this?

**Comment by xingdi1990** [comment]
git clone --branch face --recursive git@github.com:tornadomeet/mxnet.git mxnet4face
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by xingdi1990** [comment]
git clone --branch face --recursive https://github.com/tornadomeet/mxnet.git

solve it.

**Comment by xingdi1990** [comment]
but i still got "Failed loading Op Moon of type MoonOutput: [01:03:19] src/operator/operator.cc:19: Cannot find Operator MoonOutput in registry"

Same situation here

**Comment by anandbhattad** [comment]
Cannot reproduce/train either!
