### ISSUE TITLE
关于mxnet-face

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [tornadomeet/mxnet-face#2]
请问你所用的mxnet都做了哪些修改？
因为我两三个前页尝试过用mxnet实现lightcnn但是失败了，很想知道为什么会失败。

**Comment by tornadomeet** [comment]
hello,i only changed the lr and batchsize from its orinigal paper,because i use multigpu for training. so whats failure do you mean in your training?

**Comment by tornadomeet** [comment]
i only add stop_factor_lr when use factor lr,please look #1

**Comment by ZHAIXINGZHAIYUE** [comment]
你怎么把MXNET用的这么6?

**Comment by tornadomeet** [comment]
because MXNet is a cool tool for dl.:)

**Comment by ZHAIXINGZHAIYUE** [comment]
你是按照设什么标准进行人脸的矫正的呢？

**Comment by tornadomeet** [comment]
@ZHAIXINGZHAIYUE  in the training phase, please refer to [lfw.py](https://github.com/tornadomeet/mxnet-face/blob/master/lfw.py), and in the testing phase, first use lfw.py to detect and align, then correct some error detection by hand(this is usually occur when two man in the lfw image, but the detection get the wrong face ).

**Comment by ZHAIXINGZHAIYUE** [comment]
请教你个问题，为什么要把144＊144大小的图像随机crop到128*128？随机crop的作用和好处到底是什么呢？谢谢。

**Comment by tornadomeet** [comment]
data augment
