### ISSUE TITLE
time cost

### ISSUE THREAD

**Issue by perp** [tornadomeet/mxnet-face#20]
Thanks for sharing the code for face recognition.
On my android phone I exact the feature of one 128x128 image takes about 700ms.
and I test it on my laptop (CPU Only)it take about 570ms much slower than your python code about 250ms on one face.
Do you have any idea why the speed is slower ,I compiled OpenBLAS for android with USE_OPENMP?

**Comment by tornadomeet** [comment]
@perp  i 'm not familiar with compile on mobile  devices, but as i know, in an android platform, it will take about 300ms if not optimized the code.

**Comment by perp** [comment]
perhaps I didn't compile the code appropriately

**Comment by perp** [comment]
On my laptop I changed the USE_BLAS in makefile and sucessfully run face recognition on four threads the time cost of network forward time reducing from 570ms to 190ms.
But on my android phone i included openblas but it just run on one cpu(totally 8 cpu, Qualcomm 810).
  the symbols of libmxnet_predict.so as below, It seems OpenBLAS has been compiled in it.
  2678: 001f1998    20 FUNC    GLOBAL DEFAULT   11 goto_get_num_procs
  2679: 001f19ac     4 FUNC    GLOBAL DEFAULT   11 openblas_fork_handler
  2680: 001f19b0    96 FUNC    GLOBAL DEFAULT   11 blas_get_cpu_number
  2681: 001f1ee0    20 FUNC    GLOBAL DEFAULT   11 openblas_omp_num_threads_
  2682: 0022c81c     4 OBJECT  GLOBAL DEFAULT   21 blas_num_threads
  2683: 001f1a10     4 FUNC    GLOBAL DEFAULT   11 openblas_get_num_procs
  2684: 001f1a14    28 FUNC    GLOBAL DEFAULT   11 openblas_get_num_threads  
  2685: 00000000     0 FUNC    GLOBAL DEFAULT  UND printf@LIBC (2)
  2686: 001f1d7c    12 FUNC    GLOBAL DEFAULT   11 blas_memory_alloc_nolock
  2687: 001f1d88     4 FUNC    GLOBAL DEFAULT   11 blas_memory_free_nolock
  2688: 001f1d8c   208 FUNC    GLOBAL DEFAULT   11 blas_shutdown
  2689: 001f2548    84 FUNC    GLOBAL DEFAULT   11 blas_thread_shutdown_
  2690: 0005cbb8   124 FUNC    GLOBAL DEFAULT   11 gotoblas_init
  2691: 001f1ef4   300 FUNC    GLOBAL DEFAULT   11 openblas_read_env
  2692: 001f2474   212 FUNC    GLOBAL DEFAULT   11 blas_thread_init
  2693: 0022c850     4 OBJECT  GLOBAL DEFAULT   21 blas_server_avail
  2694: 00056378    44 FUNC    GLOBAL DEFAULT   11 gotoblas_quit
  2695: 0022c818     4 OBJECT  GLOBAL DEFAULT   21 hugetlb_allocated
  2696: 001f1e5c    36 FUNC    GLOBAL DEFAULT   11 __xerbla
  2697: 001f1e80    16 FUNC    GLOBAL DEFAULT   11 openblas_verbose
  2698: 001f1e90    20 FUNC    GLOBAL DEFAULT   11 openblas_thread_timeout
  2699: 001f1ea4    20 FUNC    GLOBAL DEFAULT   11 openblas_block_factor
  2700: 001f1eb8    20 FUNC    GLOBAL DEFAULT   11 openblas_num_threads_env
  2701: 001f1ecc    20 FUNC    GLOBAL DEFAULT   11 openblas_goto_num_threads

**Comment by perp** [comment]
I used caffe android, It takes 250ms for processing an image
