### ISSUE TITLE
How to transpose GPU like param file to CPU param file

### ISSUE THREAD

**Issue by arlose** [tornadomeet/mxnet-face#21]
when i use cpu mode amalgamation to forward the trained net, i can use the  lightened_cnn_cpu-0166.params, but can't use lightened_cnn-0166.params, it says:
mxnet_predict-all.cc:569: [09:58:51] mxnet_predict-all.cc:17594: GPU is not enabled
mxnet_predict-all.cc:569: [09:58:51] mxnet_predict-all.cc:18433: GPU is not enabled
terminate called after throwing an instance of 'dmlc::Error'
  what():  [09:58:51] mxnet_predict-all.cc:18433: GPU is not enabled

how do i train a CPU like params? Only use CPU? It will cost a lot of time?
or can i transpose a GPU params to CPU params? how? Thanks!

**Comment by tornadomeet** [comment]
`i can use the lightened_cnn_cpu-0166.params, but can't use lightened_cnn-0166.params` so what's mean?

**Comment by arlose** [comment]
oh, i see the #8 
that will solve my issue, thanks
