### ISSUE TITLE
编译windows版的mxnet-face时遇到的问题

### ISSUE THREAD

**Issue by buaaswf** [tornadomeet/mxnet-face#22]
严重性   代码  说明  项目  文件  行 禁止显示状态
错误  LNK1181 无法打开输入文件“dmlc-core\Release\dmlccore.lib”    mxnet   E:\swfface\mxnet-face\build\LINK    1

**Comment by tornadomeet** [comment]
hi, mxnet-face need not build, because all code is written by python, what's you need build is MXNet, http://mxnet.readthedocs.io/en/latest/how_to/build.html
