### ISSUE TITLE
compile modified mxnet for android

### ISSUE THREAD

**Issue by charleslipku** [tornadomeet/mxnet-face#24]
Since I use your modified mxnet package, I am wondering whether I can still conduct prediction on Android if I use your modified mxnet package to compile for android. @tornadomeet

**Comment by tornadomeet** [comment]
yes, you only need to copy 3 files bellow to the current master mxnet/src/operator, and rebuild again.
https://github.com/tornadomeet/mxnet/blob/face/src/operator/moon_output-inl.h
https://github.com/tornadomeet/mxnet/blob/face/src/operator/moon_output.cc
https://github.com/tornadomeet/mxnet/blob/face/src/operator/moon_output.cu

nothing else need done.

**Comment by charleslipku** [comment]
All right. But I guess the src.txt is still required when I conduct prediction on Android, is that right?

**Comment by tornadomeet** [comment]
@charleslipku  oh, if you only use the model to predict, you do not need the `moon` code, also no need src_dict.txt.  
please ref. https://github.com/tornadomeet/mxnet-face/blob/master/attribute/predict.py#L12, the symbol of lightened_moon_feature() do not contain the `moon op`, so this is not need in prediction.  
but the *-symobl.json file(i provided) should have `moon` in it, so you need to create a new *-symbol.json file, which can be done by save the symbol file of lightened_moon_feature().

**Comment by charleslipku** [comment]
So you mean if just conduct prediction, the moon operator is not needed?
But I get confused about save moon in the symbol file. Could you explain a
little bit more.

Thanks

On September 22, 2016 at 3:09:19 AM, Wei Wu (notifications@github.com)
wrote:

@charleslipku https://github.com/charleslipku oh, if you only use the
model to predict, you do not need the moon code, also no need src_dict.txt.

please ref.
https://github.com/tornadomeet/mxnet-face/blob/master/attribute/predict.py#L12,
the symbol of lightened_moon_feature() do not contain the moon op, so this
is not need in prediction.

but the *-symobl.json file(i provided) should have moon in it, so you need
to create a new *-symbol.json file, which can be done by save the symbol
file of lightened_moon_feature().

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/tornadomeet/mxnet-face/issues/24#issuecomment-248838418,
or mute the thread

**Comment by tornadomeet** [comment]
@charleslipku  yes, just like doing this:

``` python
import mxnet as mx
from lightened_moon import lightened_moon_feature
symbol = lightened_moon_feature(num_classes=40, use_fuse=True)
symbol.save("new-symbol.json")
```

then the the json file will have no moon in it.

**Comment by charleslipku** [comment]
@tornadomeet thanks for your response. Is the new-symbol.json same as the one generated during the training process? So I can use this new-symbol.json with trained params file to conduct predictions, without src_dict and moon operator.?

Thanks

On September 22, 2016 at 8:03:13 PM, Wei Wu (notifications@github.com) wrote:

@charleslipku yes, just like doing this:

import mxnet as mx
from lightened_moon import lightened_moon_feature
symbol = lightened_moon_feature(num_classes=40, use_fuse=True)
symbol.save("new-symbol.json")
then the the json file will have no moon in it.

**Comment by tornadomeet** [comment]
yes.

**Comment by charleslipku** [comment]
Thanks. If I can run my code successful on Android, I will put it on Github
and make you know.

On September 22, 2016 at 9:51:44 PM, Wei Wu (notifications@github.com)
wrote:

yes.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/tornadomeet/mxnet-face/issues/24#issuecomment-249089084,
or mute the thread

**Comment by charleslipku** [comment]
@tornadomeet I saved new-symbol.json file, and try to conduct prediction on PC with pre-trained params. But I get another error. Do you know what is wrong with that?

**src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch**

**Comment by charleslipku** [comment]
Also, I found that new-symbol.json is much bigger than the original one.

**Comment by tornadomeet** [comment]
i dont't know what's wrong. which mxnet version do you use?

**Comment by charleslipku** [comment]
I use the mxnet from your face branch.

On September 24, 2016 at 10:57:16 PM, Wei Wu (notifications@github.com)
wrote:

i dont't know what's wrong. which mxnet version do you use?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/tornadomeet/mxnet-face/issues/24#issuecomment-249401246,
or mute the thread
