### ISSUE TITLE
Change Moonoutput to SoftmaxOutput

### ISSUE THREAD

**Issue by charleslipku** [tornadomeet/mxnet-face#26]
@tornadomeet I try to train my own model using SoftmaxOutput instead of MoonOutput. Can I still use the same network architecture and similar hyper parameters? Could you give me some tips on this? Since I tried several times, but he prediction is always NaN.

**Comment by tornadomeet** [comment]
`SoftmaxOutput` do not support your problem.

**Comment by charleslipku** [comment]
Then what other options are suitable for my problem instead of MoonOutput?
How about LogisticrRegression?

On September 25, 2016 at 11:52:32 PM, Wei Wu (notifications@github.com)
wrote:

SoftmaxOutput do not support your problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/tornadomeet/mxnet-face/issues/26#issuecomment-249479004,
or mute the thread

**Comment by charleslipku** [comment]
Could you give me some suggestions about my problem? Thanks.

On September 26, 2016 at 12:08:24 AM, ANG LI (charleslipku@gmail.com) wrote:

Then what other options are suitable for my problem instead of MoonOutput?
How about LogisticrRegression?

On September 25, 2016 at 11:52:32 PM, Wei Wu (notifications@github.com)
wrote:

SoftmaxOutput do not support your problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/tornadomeet/mxnet-face/issues/26#issuecomment-249479004,
or mute the thread

**Comment by tornadomeet** [comment]
sorry, i don't know.
