### ISSUE TITLE
Faster R-CNN detection is too slow, sym.bind() cost about 28s

### ISSUE THREAD

**Issue by JalongMa** [tornadomeet/mxnet-face#27]
I test the time of sym.bind(), it cost about 28s with GPU and cudnn4. This is too slow. What's wrong with this function ?

**Comment by tornadomeet** [comment]
so strange!  what's the image size?
less than 1s here.

**Comment by JalongMa** [comment]
@tornadomeet short size is 600, max size is less than 1000, keep the default value.

**Comment by tornadomeet** [comment]
have you used https://github.com/tornadomeet/mxnet-face/blob/master/detection/demo.sh#L3 ? if not used NaiveEngine, then the time count is wrong.

**Comment by JalongMa** [comment]
@tornadomeet Thanks your answer very much ! I git a new version mxnet and rebuild it. This problem is sloved. Thanks your code !

**Comment by JalongMa** [comment]
@tornadomeet There is one more question. Where can i find the complete API references of MXNet python package ? I can not find them in official website of MXNet.........

**Comment by tornadomeet** [comment]
here, http://mxnet.io/packages/python/index.html#python-api-reference

**Comment by JalongMa** [comment]
@tornadomeet Thanks a lot !
