### ISSUE TITLE
demo.sh ran into error

### ISSUE THREAD

**Issue by wjtan99** [tornadomeet/mxnet-face#41]
My env is Ubuntu 14.04, Python 3.4, CUDA8.0.   I have the following errors, 

(mxnet) ubuntu@deepcam:~/mxnet-face/detection$ ./demo.sh 
[15:07:06] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [15:07:06] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/././json.h:639: Check failed: ch == '{' (60 vs. {) Error at Line 0, around ^`!DOCTYPE html><html lang="en" xmlns:fb="http://ogp.me/ns/fb#" x`, Expect '{' but get '<'

Stack trace returned 10 entries:
[bt] (0) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7f9849e697cc]
[bt] (1) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d7b7ff) [0x7f984ca0f7ff]
[bt] (2) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d88c56) [0x7f984ca1cc56]
[bt] (3) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d82ec6) [0x7f984ca16ec6]
[bt] (4) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0xf9aa1f) [0x7f984ac2ea1f]
[bt] (5) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d58f78) [0x7f984c9ecf78]
[bt] (6) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0xf94ead) [0x7f984ac28ead]
[bt] (7) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0xf9aa1f) [0x7f984ac2ea1f]
[bt] (8) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d58f78) [0x7f984c9ecf78]
[bt] (9) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0xe0fcae) [0x7f984aaa3cae]

Traceback (most recent call last):
  File "detection.py", line 97, in <module>
    main()
  File "detection.py", line 47, in main
    _, arg_params, aux_params = mx.model.load_checkpoint(args.prefix, args.epoch)
  File "/home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/model.py", line 394, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/symbol.py", line 1900, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/base.py", line 129, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:07:06] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/././json.h:639: Check failed: ch == '{' (60 vs. {) Error at Line 0, around ^`!DOCTYPE html><html lang="en" xmlns:fb="http://ogp.me/ns/fb#" x`, Expect '{' but get '<'

Stack trace returned 10 entries:
[bt] (0) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7f9849e697cc]
[bt] (1) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d7b7ff) [0x7f984ca0f7ff]
[bt] (2) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d88c56) [0x7f984ca1cc56]
[bt] (3) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d82ec6) [0x7f984ca16ec6]
[bt] (4) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0xf9aa1f) [0x7f984ac2ea1f]
[bt] (5) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d58f78) [0x7f984c9ecf78]
[bt] (6) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0xf94ead) [0x7f984ac28ead]
[bt] (7) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0xf9aa1f) [0x7f984ac2ea1f]
[bt] (8) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0x2d58f78) [0x7f984c9ecf78]
[bt] (9) /home/ubuntu/anaconda3/envs/mxnet/lib/python3.4/site-packages/mxnet/libmxnet.so(+0xe0fcae) [0x7f984aaa3cae]

[15:07:06] src/engine/engine.cc:54: MXNet start using engine: NaiveEngine
[15:07:06] src/engine/naive_engine.cc:53: Engine shutdown

Can somebody help take a look at what it is?  What is correct env to make it run?  
Thanks a lot.

**Comment by shipengai** [comment]
How do you solve it? I have the same error. Thanks

**Comment by wjtan99** [comment]
I do not remember the details. Recently I revisited this repo and used python 2.7, then there was no such error.
