### ISSUE TITLE
Error running test.sh

### ISSUE THREAD

**Issue by vic-w** [tornadomeet/mxnet-face#5]
I tried testing the model on lfw and got the following error message.

Here is what I've done:
1. modified the test.sh. Changed align_data_path to my own folder which contains aligned lfw images of size 96*96
2. modified the default size to 96
3. deleted the predict.txt
4. ran ./test.sh

> INFO:root:Namespace(epoch=166, lfw_align='/home/vic/Projects/openface/data/lfw/dlib-affine-sz:96', model_prefix='../model/lightened_cnn/lightened_cnn', pairs='./pairs.txt', predict_file='./predict.txt', size=96, suffix='png')
> Loading embeddings done
> INFO:root:begin generate the predict.txt.
> ...Reading pairs.
> INFO:root:processing name1:Abel_Pacheco/Abel_Pacheco_0001.png <---> name2:Abel_Pacheco/Abel_Pacheco_0004.png
> Traceback (most recent call last):
>   File "lfw.py", line 152, in <module>
>     main()
>   File "lfw.py", line 147, in main
>     get_predict_file(args)
>   File "lfw.py", line 103, in get_predict_file
>     exector = symbol.bind(ctx, model_args ,args_grad=None, grad_req="null", aux_states=model_auxs)
>   File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 839, in bind
>     ctypes.byref(handle)))
>   File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
>     raise MXNetError(py_str(_LIB.MXGetLastError()))
> mxnet.base.MXNetError: InferShape Error in fc1's weight argument
> Corresponding keyword of symbol: fc1_weight
> Shape inconsistent, Provided =(512,2048), inferred shape=(512,1152)

**Comment by tornadomeet** [comment]
@vic-w hello, the face identification model needs 128x128 image size, so you'd better add the resize code after read the image. because i just aligned the image to 128x128, so i had not add that code. You are also welcome to contribute the code~

**Comment by tornadomeet** [comment]
@vic-w  i also provided the aligned lfw dataset just now, you can check in the readme file.
