### ISSUE TITLE
gpu not enabled error

### ISSUE THREAD

**Issue by westpilgrim** [tornadomeet/mxnet-face#8]
hi , I used your face identification model : lightened_cnn-0166.params lightened_cnn-symbol.json using mxnet's cpp example  image-classification-predict.cc ,but got an error at 'MXPredCreate" ,it returned -1 and gives the following error:

[13:55:10] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [13:55:10]D:\chhong\mxnet\src\ndarray\ndarray.cc:283: GPU is not enabled

I did not forget to set int dev_type = 1;
 I use the mxnet cpu-only binaries : 20160419_win10_x64_cpu_only.7z

IF i use the default model Inception_BN-symbol.json Inception_BN-0039.params ,everything is OK.

so whats the problem? How to run your model on cpu-only machines?

**Comment by westpilgrim** [comment]
I found these words :change the model context on gpu0
do you have the old version of model that do not use the gpu context?

**Comment by tornadomeet** [comment]
you have no gpu there?
if that i'll upload the cpu version model this weekend.

**Comment by westpilgrim** [comment]
非常感谢！

**Comment by westpilgrim** [comment]
作者大神快点上传吧！周末已经过啦！哈哈：）

**Comment by tornadomeet** [comment]
@westpilgrim  sorry be late. had done! you can test it.  
i also add the tools for user to convert the model by itself:https://github.com/tornadomeet/mxnet-face/blob/master/util/chdevice.py

**Comment by westpilgrim** [comment]
thx
